#!/usr/bin/env python3
"""Summarize QueryNode path-hit ratios and hypothetical QPS benefit.

Input CSVs are generated by analyze_minio_trace.py:
  <prefix>.request.csv
  <prefix>.access.csv
  <prefix>.remote.csv

This script intentionally uses only the Python standard library.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Set


READ_EVENTS = {"read_done", "legacy_size_done"}


def to_float(value: Any, default: float = 0.0) -> float:
    if value is None or value == "":
        return default
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def to_int(value: Any, default: int = 0) -> int:
    if value is None or value == "":
        return default
    try:
        return int(value)
    except (TypeError, ValueError):
        try:
            return int(float(value))
        except (TypeError, ValueError):
            return default


def to_bool(value: Any, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if value is None or value == "":
        return default
    text = str(value).strip().lower()
    if text in {"true", "1", "yes", "y"}:
        return True
    if text in {"false", "0", "no", "n"}:
        return False
    return default


def mib(value: float) -> float:
    return value / 1024.0 / 1024.0


def read_csv(path: Optional[Path]) -> List[Dict[str, str]]:
    if path is None or not path.exists():
        return []
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def csv_path(prefix: Optional[str], explicit: Optional[str], suffix: str) -> Optional[Path]:
    if explicit:
        return Path(explicit)
    if prefix:
        return Path(f"{prefix}.{suffix}.csv")
    return None


def non_empty_ids(records: Sequence[Dict[str, Any]], key: str) -> Set[str]:
    values: Set[str] = set()
    for record in records:
        value = record.get(key)
        if value is None or value == "":
            continue
        if key == "msg_id" and to_int(value, 0) <= 0:
            continue
        values.add(str(value))
    return values


def choose_join_key(request_records: Sequence[Dict[str, Any]], miss_records: Sequence[Dict[str, Any]], requested: str) -> str:
    if requested != "auto":
        return requested
    if non_empty_ids(request_records, "trace_id") and non_empty_ids(miss_records, "trace_id"):
        return "trace_id"
    if non_empty_ids(request_records, "msg_id") and non_empty_ids(miss_records, "msg_id"):
        return "msg_id"
    return ""


def search_request_denominator(request_records: Sequence[Dict[str, Any]]) -> List[Dict[str, Any]]:
    search_records = [row for row in request_records if row.get("operation") == "search"]
    root_records = [row for row in search_records if row.get("entry") == "search"]
    worker_records = [row for row in search_records if row.get("entry") == "search_segments"]
    return root_records or worker_records or search_records


def max_group_size_by_id(records: Sequence[Dict[str, Any]], key: str) -> Dict[str, int]:
    result: Dict[str, int] = {}
    if not key:
        return result
    for record in records:
        value = record.get(key)
        if value is None or value == "":
            continue
        value = str(value)
        if key == "msg_id" and to_int(value, 0) <= 0:
            continue
        group_size = max(to_int(record.get("group_size"), 1), 1)
        result[value] = max(result.get(value, 0), group_size)
    return result


def max_wait_ms_by_id(records: Sequence[Dict[str, Any]], key: str) -> Dict[str, float]:
    result: Dict[str, float] = {}
    if not key:
        return result
    for record in records:
        value = record.get(key)
        if value is None or value == "":
            continue
        value = str(value)
        if key == "msg_id" and to_int(value, 0) <= 0:
            continue
        wait_ms = to_float(record.get("wait_cache_ms"), 0.0)
        if wait_ms <= 0:
            wait_ms = to_float(record.get("duration_ms"), 0.0)
        result[value] = max(result.get(value, 0.0), wait_ms)
    return result


def summarize_remote(remote_records: Sequence[Dict[str, Any]]) -> Dict[str, Any]:
    read_records = [row for row in remote_records if row.get("event") in READ_EVENTS]
    decode_records = [row for row in remote_records if row.get("event") == "decode_done"]
    read_bytes = sum(to_float(row.get("encoded_bytes"), 0.0) for row in read_records)
    decoded_bytes = sum(to_float(row.get("decoded_bytes"), 0.0) for row in decode_records)
    read_ms = sum(max(to_float(row.get("duration_ms"), 0.0), 0.0) for row in read_records)
    return {
        "remote_read_records": len(read_records),
        "remote_read_mib": mib(read_bytes),
        "remote_decode_records": len(decode_records),
        "remote_decoded_mib": mib(decoded_bytes),
        "remote_read_duration_ms_sum": read_ms,
    }


def estimate_qps(old_qps: Optional[float], path_speedup: Optional[float], path_fraction: Optional[float]) -> Dict[str, Any]:
    if old_qps is None or path_speedup is None or path_fraction is None:
        return {}
    if old_qps <= 0 or path_speedup <= 0:
        return {}
    path_fraction = min(max(path_fraction, 0.0), 1.0)
    denominator = 1.0 - path_fraction + path_fraction / path_speedup
    if denominator <= 0:
        return {}
    new_qps = old_qps / denominator
    return {
        "old_qps": old_qps,
        "path_speedup": path_speedup,
        "path_fraction_used": path_fraction,
        "estimated_new_qps": new_qps,
        "estimated_qps_gain_ratio": new_qps / old_qps,
        "estimated_qps_gain_percent": (new_qps / old_qps - 1.0) * 100.0,
    }


def build_summary(
    request_records: Sequence[Dict[str, Any]],
    access_records: Sequence[Dict[str, Any]],
    remote_records: Sequence[Dict[str, Any]],
    id_key_arg: str,
    old_qps: Optional[float],
    old_avg_latency_ms: Optional[float],
    path_speedup: Optional[float],
    path_fraction_arg: Optional[float],
) -> Dict[str, Any]:
    denominator_records = search_request_denominator(request_records)
    search_access_records = [row for row in access_records if row.get("operation") == "search" and row.get("trace_kind") == "segment_access"]
    miss_records = [row for row in search_access_records if to_bool(row.get("cache_miss"), False)]

    join_key = choose_join_key(denominator_records, miss_records, id_key_arg)
    request_ids = non_empty_ids(denominator_records, join_key) if join_key else set()
    miss_ids = non_empty_ids(miss_records, join_key) if join_key else set()
    hit_ids = request_ids & miss_ids

    request_count = len(request_ids) if request_ids else len(denominator_records)
    hit_count = len(hit_ids) if request_ids else 0
    group_size_by_id = max_group_size_by_id(miss_records, join_key)
    wait_ms_by_id = max_wait_ms_by_id(miss_records, join_key)

    group_size_hit_count = 0
    total_weighted_wait_ms = 0.0
    if request_ids:
        for request_id in request_ids:
            group_size = group_size_by_id.get(request_id, 0)
            if group_size <= 0:
                continue
            group_size_hit_count += group_size
            total_weighted_wait_ms += wait_ms_by_id.get(request_id, 0.0) * group_size
        group_size_hit_count = min(group_size_hit_count, request_count)

    request_hit_ratio = hit_count / request_count if request_count else 0.0
    group_size_hit_ratio = group_size_hit_count / request_count if request_count else 0.0
    segment_cache_miss_ratio = len(miss_records) / len(search_access_records) if search_access_records else 0.0

    estimated_path_fraction = path_fraction_arg
    if estimated_path_fraction is None and old_avg_latency_ms and old_avg_latency_ms > 0 and request_count > 0:
        estimated_path_fraction = min(total_weighted_wait_ms / (request_count * old_avg_latency_ms), 1.0)

    summary: Dict[str, Any] = {
        "join_key": join_key or "none",
        "search_request_records": len(denominator_records),
        "search_request_count": request_count,
        "search_segment_access_records": len(search_access_records),
        "search_cache_miss_segment_access_records": len(miss_records),
        "search_segment_cache_miss_ratio": segment_cache_miss_ratio,
        "search_cache_miss_request_count": hit_count,
        "search_cache_miss_request_ratio": request_hit_ratio,
        "search_cache_miss_request_group_size_estimate": group_size_hit_count,
        "search_cache_miss_request_group_size_ratio": group_size_hit_ratio,
        "cache_miss_request_wait_ms_sum_estimate": total_weighted_wait_ms,
        "estimated_path_fraction_from_latency": estimated_path_fraction,
    }
    summary.update(summarize_remote(remote_records))
    summary.update(estimate_qps(old_qps, path_speedup, estimated_path_fraction))
    return summary


def print_summary(summary: Dict[str, Any]) -> None:
    print("QueryNode Path Benefit Summary")
    print("==============================")
    for key in [
        "join_key",
        "search_request_count",
        "search_cache_miss_request_count",
        "search_cache_miss_request_ratio",
        "search_cache_miss_request_group_size_estimate",
        "search_cache_miss_request_group_size_ratio",
        "search_segment_access_records",
        "search_cache_miss_segment_access_records",
        "search_segment_cache_miss_ratio",
        "cache_miss_request_wait_ms_sum_estimate",
        "estimated_path_fraction_from_latency",
        "remote_read_records",
        "remote_read_mib",
        "remote_read_duration_ms_sum",
        "estimated_new_qps",
        "estimated_qps_gain_percent",
    ]:
        if key in summary:
            value = summary[key]
            if isinstance(value, float):
                print(f"{key}: {value:.6f}")
            else:
                print(f"{key}: {value}")


def write_summary_csv(path: str, summary: Dict[str, Any]) -> None:
    with open(path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=sorted(summary.keys()))
        writer.writeheader()
        writer.writerow(summary)


def main() -> int:
    parser = argparse.ArgumentParser(description="Summarize QueryNode path-hit ratios and hypothetical QPS benefit.")
    parser.add_argument("--csv-prefix", help="Prefix used by analyze_minio_trace.py --csv-prefix.")
    parser.add_argument("--request-csv", help="Explicit request.csv path.")
    parser.add_argument("--access-csv", help="Explicit access.csv path.")
    parser.add_argument("--remote-csv", help="Explicit remote.csv path.")
    parser.add_argument("--id-key", choices=["auto", "trace_id", "msg_id"], default="auto", help="Request/access join key.")
    parser.add_argument("--old-qps", type=float, help="Measured baseline VectorDBBench QPS.")
    parser.add_argument("--old-avg-latency-ms", type=float, help="Measured baseline average latency. Used to estimate path fraction.")
    parser.add_argument("--path-speedup", type=float, help="FPGA/prototype speedup for the optimized path.")
    parser.add_argument("--path-fraction", type=float, help="Override path time fraction F directly.")
    parser.add_argument("--json-out", help="Write summary JSON.")
    parser.add_argument("--summary-csv", help="Write one-row summary CSV.")
    args = parser.parse_args()

    request_csv = csv_path(args.csv_prefix, args.request_csv, "request")
    access_csv = csv_path(args.csv_prefix, args.access_csv, "access")
    remote_csv = csv_path(args.csv_prefix, args.remote_csv, "remote")

    request_records = read_csv(request_csv)
    access_records = read_csv(access_csv)
    remote_records = read_csv(remote_csv)

    if not request_records:
        print("warning: no request records loaded; request-level ratios may be unavailable", file=sys.stderr)
    if not access_records:
        print("warning: no access records loaded; cache-miss ratios may be unavailable", file=sys.stderr)

    summary = build_summary(
        request_records=request_records,
        access_records=access_records,
        remote_records=remote_records,
        id_key_arg=args.id_key,
        old_qps=args.old_qps,
        old_avg_latency_ms=args.old_avg_latency_ms,
        path_speedup=args.path_speedup,
        path_fraction_arg=args.path_fraction,
    )
    print_summary(summary)

    if args.json_out:
        with open(args.json_out, "w", encoding="utf-8") as handle:
            json.dump(summary, handle, ensure_ascii=False, indent=2)
    if args.summary_csv:
        write_summary_csv(args.summary_csv, summary)

    return 0


if __name__ == "__main__":
    sys.exit(main())
